services:
  - type: web
    name: musication-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 300 --workers 2 --threads 4"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: musication-db
          property: connectionString
      - key: BASE_URL
        sync: false
      - key: FRONTEND_URL
        value: https://musicationapp.netlify.app

databases:
  - name: musication-db
    databaseName: musication
    user: musication
